export const COLOR_HEX: Record<string, string> = {
  Black: '#0a0a0a', White: '#ffffff', Navy: '#1f2a44', Beige: '#d9c7a3', Camel: '#c19a6b',
  Tan: '#d2b48c', Brown: '#5a3825', Olive: '#6b6b47', Grey: '#808080', 'Grey Melange': '#9a9a9a',
  Ivory: '#fffff0', Emerald: '#046307', Burgundy: '#5e1f2e', Blush: '#f4c2c2', Gold: '#c9a96e',
  Silver: '#c0c0c0', 'Rose Gold': '#b76e79', Red: '#b22222', Nude: '#e3bc9a', Sage: '#9caf88',
  Cream: '#f5f0e1', Lilac: '#c8a2c8', Indigo: '#3f5d7d', 'Light Wash': '#a9c1d9', Onyx: '#353839',
  'Jet Black': '#0b0b0b', Cognac: '#834333', 'Sky Blue': '#87ceeb', Charcoal: '#36454f',
  Khaki: '#c3b091', 'Two-Tone': '#b0a080', Natural: '#e8e0d0', Sand: '#dcc7a1', Coral: '#ff7f50',
  Mint: '#aaf0d1',
};

export interface CategorySeed {
  slug: string;
  imageGroup: string;
  skuPrefix: string;
  priceRange: [number, number];
  materials: string[];
  sizeOptions: string[] | null;
  colors: string[];
  products: string[];
}

export const CATEGORY_SEEDS: CategorySeed[] = [
  {
    slug: 'mens-ready-to-wear-shirts', imageGroup: 'mensShirts', skuPrefix: 'MSH',
    priceRange: [8000, 25000], materials: ['Egyptian Cotton', 'Linen', 'Cotton Poplin', 'Silk Blend'],
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Sky Blue', 'Black', 'Navy', 'Beige', 'Charcoal'],
    products: ['Classic Oxford Shirt', 'Linen Resort Shirt', 'Slim Fit Poplin Shirt', 'Striped Dress Shirt',
      'Mandarin Collar Shirt', 'Chambray Casual Shirt', 'Silk Blend Evening Shirt', 'Button-Down Twill Shirt',
      'Brushed Flannel Shirt', 'Tuxedo Pleated Shirt'],
  },
  {
    slug: 'mens-t-shirts', imageGroup: 'mensTshirts', skuPrefix: 'MTP',
    priceRange: [4000, 12000], materials: ['Pima Cotton', 'Merino Wool', 'Cotton Pique'],
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Black', 'Navy', 'Grey Melange', 'Olive', 'Burgundy'],
    products: ['Classic Pique Polo', 'Crew Neck Essential Tee', 'Merino Wool Polo', 'Long Sleeve Henley',
      'Striped Polo Shirt', 'Embroidered Crest Tee', 'V-Neck Cotton Tee', 'Performance Polo',
      'Garment-Dyed Tee', 'Half-Zip Pique Shirt'],
  },
  {
    slug: 'mens-denims', imageGroup: 'mensDenims', skuPrefix: 'MDN',
    priceRange: [10000, 30000], materials: ['Japanese Selvedge Denim', 'Stretch Denim', 'Raw Denim'],
    sizeOptions: ['30', '32', '34', '36', '38'], colors: ['Indigo', 'Black', 'Light Wash', 'Grey', 'Charcoal'],
    products: ['Slim Fit Selvedge Jeans', 'Straight Leg Raw Denim', 'Tapered Stretch Jeans', 'Distressed Skinny Jeans',
      'Relaxed Fit Denim', 'Black Wash Slim Jeans', 'Vintage Wash Bootcut Jeans', 'Cropped Denim Trousers',
      'Stone Wash Straight Jeans', 'Indigo Carpenter Jeans'],
  },
  {
    slug: 'mens-suits', imageGroup: 'mensSuits', skuPrefix: 'MST',
    priceRange: [60000, 250000], materials: ['Italian Wool', 'Wool-Silk Blend', 'Linen Blend', 'Tweed'],
    sizeOptions: ['46', '48', '50', '52', '54'], colors: ['Charcoal', 'Navy', 'Black', 'Grey', 'Beige'],
    products: ['Two-Piece Wool Suit', 'Tailored Tuxedo Set', 'Linen Summer Suit', 'Double-Breasted Suit',
      'Three-Piece Pinstripe Suit', 'Slim Fit Wool Blazer Set', 'Tweed Country Suit', 'Velvet Dinner Jacket Set',
      'Checked Wool Suit', 'Cream Silk-Blend Suit'],
  },
  {
    slug: 'mens-trousers', imageGroup: 'mensTrousers', skuPrefix: 'MTR',
    priceRange: [7000, 20000], materials: ['Cotton Twill', 'Wool Flannel', 'Linen', 'Stretch Cotton'],
    sizeOptions: ['30', '32', '34', '36', '38'], colors: ['Beige', 'Navy', 'Olive', 'Grey', 'Black', 'Khaki'],
    products: ['Tailored Chino Trousers', 'Pleated Wool Trousers', 'Linen Drawstring Trousers', 'Tailored Bermuda Shorts',
      'Flat Front Dress Trousers', 'Cargo Utility Trousers', 'Cropped Cotton Trousers', 'Pinstripe Formal Trousers',
      'Corduroy Trousers', 'Linen Tailored Shorts'],
  },
  {
    slug: 'men-shoes', imageGroup: 'menShoes', skuPrefix: 'MSO',
    priceRange: [15000, 60000], materials: ['Full-Grain Leather', 'Suede', 'Patent Leather'],
    sizeOptions: ['39', '40', '41', '42', '43', '44', '45', '46'], colors: ['Black', 'Brown', 'Tan', 'Burgundy', 'Navy'],
    products: ['Classic Oxford Shoes', 'Leather Derby Shoes', 'Penny Loafers', 'Suede Chelsea Boots',
      'Monk Strap Shoes', 'Tassel Loafers', 'Double Monk Strap Shoes', 'Leather Brogues',
      'Driving Moccasins', 'Patent Leather Formal Shoes'],
  },
  {
    slug: 'mens-bags', imageGroup: 'mensBags', skuPrefix: 'MBG',
    priceRange: [25000, 120000], materials: ['Full-Grain Leather', 'Saffiano Leather', 'Canvas-Leather'],
    sizeOptions: null, colors: ['Black', 'Brown', 'Tan', 'Navy', 'Cognac'],
    products: ['Leather Briefcase', 'Messenger Bag', 'Laptop Tote', 'Weekend Duffel',
      'Document Holder Bag', 'Crossbody Satchel', 'Leather Portfolio Bag', 'Business Backpack',
      'Garment Bag', 'Leather Wallet'],
  },
  {
    slug: 'womens-dresses', imageGroup: 'womensDresses', skuPrefix: 'WDR',
    priceRange: [25000, 150000], materials: ['Silk', 'Velvet', 'Crepe', 'Chiffon', 'Lace'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Emerald', 'Burgundy', 'Ivory', 'Blush', 'Navy'],
    products: ['Silk Slip Dress', 'Velvet Evening Gown', 'Lace Cocktail Dress', 'Wrap Midi Dress',
      'Chiffon Maxi Dress', 'Tailored Sheath Dress', 'Off-Shoulder Gown', 'Pleated Satin Dress',
      'Floral Print Sundress', 'Asymmetric Draped Dress'],
  },
  {
    slug: 'womens-shirts-tops', imageGroup: 'womensTops', skuPrefix: 'WST',
    priceRange: [9000, 35000], materials: ['Silk', 'Cotton Poplin', 'Linen', 'Satin'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'], colors: ['White', 'Ivory', 'Blush', 'Black', 'Sage', 'Lilac'],
    products: ['Silk Button-Down Blouse', 'Cotton Poplin Shirt', 'Satin Camisole Top', 'Linen Wrap Top',
      'Ruffle Sleeve Blouse', 'Tie-Neck Silk Top', 'Cropped Knit Top', 'Off-Shoulder Top',
      'Pleated Chiffon Blouse', 'Tailored Tunic Top'],
  },
  {
    slug: 'womens-skirts', imageGroup: 'womensSkirts', skuPrefix: 'WSK',
    priceRange: [12000, 40000], materials: ['Wool', 'Silk', 'Pleated Satin', 'Linen'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Beige', 'Navy', 'Camel', 'Ivory'],
    products: ['Pleated Midi Skirt', 'A-Line Wool Skirt', 'Satin Wrap Skirt', 'Linen Maxi Skirt',
      'High-Waisted Pencil Skirt', 'Tiered Chiffon Skirt', 'Leather-Trim Mini Skirt', 'Asymmetric Hem Skirt',
      'Tweed Box-Pleat Skirt', 'Silk Slip Skirt'],
  },
  {
    slug: 'womens-T-shirts-sweatshirts', imageGroup: 'womensTshirts', skuPrefix: 'WTS',
    priceRange: [6000, 25000], materials: ['Pima Cotton', 'Cashmere Blend', 'French Terry'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'], colors: ['White', 'Black', 'Grey Melange', 'Sage', 'Blush', 'Cream'],
    products: ['Cropped Cotton Tee', 'Cashmere Blend Sweatshirt', 'Oversized Crew Sweatshirt', 'Ribbed Tank Top',
      'Embroidered Detail Tee', 'Hooded Sweatshirt', 'Long Sleeve Tee', 'V-Neck Cotton Tee',
      'Relaxed Fit Sweatshirt', 'Boatneck Tee'],
  },
  {
    slug: 'womens-denims', imageGroup: 'womensDenims', skuPrefix: 'WDN',
    priceRange: [10000, 28000], materials: ['Stretch Denim', 'Selvedge Denim', 'Organic Cotton Denim'],
    sizeOptions: ['26', '28', '30', '32', '34'], colors: ['Indigo', 'Black', 'Light Wash', 'White', 'Grey'],
    products: ['High-Rise Skinny Jeans', 'Straight Leg Jeans', 'Wide Leg Denim Trousers', 'Distressed Boyfriend Jeans',
      'Cropped Flare Jeans', 'Denim Culottes', 'White Wash Skinny Jeans', 'Vintage Straight Jeans',
      'Patchwork Denim Jeans', 'High-Rise Straight Jeans'],
  },
  {
    slug: 'Women-shorts-trousers', imageGroup: 'womensTrousers', skuPrefix: 'WTR',
    priceRange: [9000, 30000], materials: ['Linen', 'Wool Crepe', 'Cotton Twill', 'Satin'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'], colors: ['Black', 'Beige', 'Ivory', 'Navy', 'Camel'],
    products: ['Tailored Wide-Leg Trousers', 'Linen Pleated Trousers', 'High-Waisted Shorts', 'Satin Palazzo Pants',
      'Cigarette Trousers', 'Cotton Twill Bermuda Shorts', 'Pinstripe Formal Trousers', 'Culotte Trousers',
      'Drawstring Linen Shorts', 'Cropped Tailored Trousers'],
  },
  {
    slug: 'women-shoes', imageGroup: 'womenShoes', skuPrefix: 'WSO',
    priceRange: [18000, 70000], materials: ['Leather', 'Suede', 'Satin', 'Patent Leather'],
    sizeOptions: ['35', '36', '37', '38', '39', '40', '41'], colors: ['Black', 'Nude', 'Red', 'Gold', 'Silver', 'Burgundy'],
    products: ['Stiletto Pumps', 'Suede Ankle Boots', 'Strappy Sandals', 'Block Heel Mules',
      'Patent Leather Flats', 'Platform Sandals', 'Knee-High Boots', 'Embellished Heels',
      'Espadrille Wedges', 'Pointed-Toe Flats'],
  },
  {
    slug: 'womens-bags', imageGroup: 'womensBags', skuPrefix: 'WBG',
    priceRange: [35000, 180000], materials: ['Calfskin Leather', 'Saffiano Leather', 'Suede', 'Quilted Leather'],
    sizeOptions: null, colors: ['Black', 'Tan', 'Cream', 'Burgundy', 'Gold'],
    products: ['Quilted Shoulder Bag', 'Structured Top-Handle Bag', 'Leather Clutch', 'Chain Strap Crossbody',
      'Mini Flap Bag', 'Soft Hobo Bag', 'Embossed Satchel', 'Evening Clutch',
      'Bucket Bag', 'Boxy Crossbody Bag'],
  },
  {
    slug: 'bags-travel', imageGroup: 'bagsTravel', skuPrefix: 'BTV',
    priceRange: [30000, 110000], materials: ['Leather', 'Nylon-Leather', 'Canvas'],
    sizeOptions: null, colors: ['Black', 'Navy', 'Tan', 'Olive', 'Grey'],
    products: ['Leather Weekender Bag', 'Wheeled Travel Trolley', 'Garment Travel Bag', 'Canvas Duffel Bag',
      'Packable Travel Tote', 'Leather Holdall', 'Cabin Carry-On Bag', 'Travel Toiletry Case',
      'Convertible Duffel Backpack', 'Expandable Suitcase'],
  },
  {
    slug: 'bags-totes', imageGroup: 'bagsTotes', skuPrefix: 'BTO',
    priceRange: [15000, 65000], materials: ['Canvas', 'Leather', 'Raffia', 'Jute'],
    sizeOptions: null, colors: ['Natural', 'Black', 'Tan', 'Navy', 'Cream'],
    products: ['Structured Leather Tote', 'Canvas Shopper Tote', 'Raffia Beach Tote', 'Reversible Tote Bag',
      'Oversized Work Tote', 'Zip-Top Leather Tote', 'Woven Jute Tote', 'Mini Tote Bag',
      'Suede Panel Tote', 'Everyday Canvas Tote'],
  },
  {
    slug: 'bags-backpacks', imageGroup: 'bagsBackpacks', skuPrefix: 'BBP',
    priceRange: [25000, 85000], materials: ['Leather', 'Nylon', 'Suede'],
    sizeOptions: null, colors: ['Black', 'Tan', 'Navy', 'Olive', 'Grey'],
    products: ['Leather Laptop Backpack', 'Drawstring Suede Backpack', 'Minimalist Day Backpack', 'Quilted Mini Backpack',
      'Convertible Backpack Tote', 'Technical Nylon Backpack', 'Rolltop Leather Backpack', 'Two-Tone Canvas Backpack',
      'Structured Commuter Backpack', 'Pocket Detail Backpack'],
  },
  {
    slug: 'watches', imageGroup: 'watches', skuPrefix: 'WAT',
    priceRange: [45000, 350000], materials: ['Stainless Steel', 'Rose Gold Plated', 'Titanium', 'Leather Strap'],
    sizeOptions: null, colors: ['Silver', 'Gold', 'Black', 'Rose Gold', 'Two-Tone'],
    products: ['Classic Chronograph Watch', 'Automatic Skeleton Watch', 'Minimalist Dress Watch', "Diver's Steel Watch",
      'Rose Gold Bracelet Watch', 'Leather Strap Dress Watch', 'Titanium Sports Watch', 'Mother-of-Pearl Dial Watch',
      'Moonphase Watch', 'Two-Tone Bracelet Watch'],
  },
  {
    slug: 'noir-series', imageGroup: 'noirSeries', skuPrefix: 'NOI',
    priceRange: [20000, 150000], materials: ['Wool', 'Silk', 'Leather', 'Cashmere'],
    sizeOptions: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Jet Black', 'Onyx'],
    products: ['Noir Tailored Blazer', 'Noir Silk Shirt', 'Noir Leather Trousers', 'Noir Evening Gown',
      'Noir Wool Coat', 'Noir Pleated Skirt', 'Noir Statement Clutch', 'Noir Cashmere Sweater',
      'Noir Tuxedo Jacket', 'Noir Ankle Boots'],
  },
  {
    slug: 'limited-edition', imageGroup: 'limitedEdition', skuPrefix: 'LTD',
    priceRange: [40000, 300000], materials: ['Silk', 'Leather', 'Cashmere', 'Wool'],
    sizeOptions: ['S', 'M', 'L'], colors: ['Black', 'Camel', 'Burgundy', 'Ivory', 'Gold'],
    products: ['Limited Edition Silk Scarf', 'Limited Edition Leather Belt', 'Limited Edition Sunglasses',
      'Limited Edition Cufflinks Set', 'Limited Edition Trench Coat', 'Limited Edition Embroidered Jacket',
      'Limited Edition Leather Gloves', 'Limited Edition Statement Necklace', 'Limited Edition Wool Cape',
      'Limited Edition Travel Wallet'],
  },
  {
    slug: 'collections-summer', imageGroup: 'summerCollection', skuPrefix: 'SUM',
    priceRange: [8000, 40000], materials: ['Linen', 'Cotton', 'Seersucker'],
    sizeOptions: ['S', 'M', 'L', 'XL'], colors: ['White', 'Sky Blue', 'Sand', 'Coral', 'Mint'],
    products: ['Linen Resort Shirt', 'Cotton Sundress', 'Seersucker Shorts', 'Linen Wide-Brim Hat',
      'Striped Cabana Shirt', 'Linen Beach Trousers', 'Cotton Poplin Shirt Dress', 'Espadrille Sandals',
      'Linen Kaftan', 'Lightweight Bomber Jacket'],
  },
];
