-- AlterTable
ALTER TABLE "site_config" ADD COLUMN     "shippingCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxLabel" TEXT NOT NULL DEFAULT 'Tax',
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
